;vector 是一个固定长度的数组,可以存放任意的内容
;list不一样的是,vector的访问时间是一个常数,还可以更新其内容
#lang racket

;;定义一个vector
#("a" 'i 'b 3)

;;vector 作为一个表达式的时候可以指定其长度
 #4(baldwin bruce)
;;当长度不够时,似乎会以最后一个元素填充

;; #2(12 3 3 4 4 5)
;;当指定的元素数量比所给的多的时候会报错

;;还有一个隐式的规则
'#(name (that tune))
;这样的定义就会使(that tune)也是一个vector
;就是说其中的内容是嵌套定义的

(vector-ref #(1 2 3 4 5 56) 0)


;;vector和list可以通过 vector->list 和list->vector 方便地进行转换
;循环时分配新的list有时候代价太大,这时候可以考虑使用 for/fold
;它对list 和vector 都适用
(list->vector (map string-titlecase
                     (vector->list #("three" "blind" "mice"))))

;;两个vector 是equal? 的  <==> 长度和元素 是equal?的
;;vector 可以被用作序列
;; Vectors generated by the default reader (see Reading Strings) are immutable.


(display #4(1 2))

(vector->list #4(1 2))


;;构造器
(vector v ...)

;;谓词
;; (vector? v)

